### ISSUE TITLE
How can I translate it into Traditional Chinese?

### ISSUE THREAD

**Issue by angela0930** [ddomino007/WebConsole-electron-client#1]
How can I translate it into Traditional Chinese?
I see that only have Simplified Chinese here.

**Comment by angela0930** [comment]
> How can I translate it into Traditional Chinese? I see that only have Simplified Chinese here.

**Comment by BenjiThatFoxGuy** [comment]
please submit translations to https://github.com/mesacarlos/WebConsole
I might incorporate them when I get the time, alongside with implementing the new ui
